name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"  # Debian 10
          - "3.13"  # Debian 13

    steps:
    - uses: actions/checkout@v6

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies (apt)
      run: |
        sudo apt-get -q install -y \
          libsctp-dev \
          mariadb-server \
          postgresql \
          redis

    - name: Install dependencies (pip)
      run: |
        python -m pip install --upgrade pip
        # psycopg2: test_database_upgrade_postgresql.py
        pip install \
          -r requirements.txt \
          -r requirements-test.txt \
          psycopg2

    - name: Run PyHSS tests
      run: |
        export PYTEST_ADDOPTS="--color=yes"
        pytest -xvv
